import { CodeGenerator } from './registry.js';
import { ActionScaffold } from '../skills.js';
import { MachineDef } from '../parser/ast.js';

export class TypeScriptCodeGenerator implements CodeGenerator {
  name(): string {
    return 'typescript';
  }

  generate(actions: ActionScaffold[], machine: MachineDef): string {
    const lines: string[] = [
      `// Generated by Orca`,
      `// Machine: ${machine.name}`,
      '',
      `export interface Context {`,
    ];

    // Generate context type from machine context
    for (const field of machine.context) {
      if (field.type) {
        lines.push(`  ${field.name}: ${field.type};`);
      } else {
        lines.push(`  ${field.name}: string | number | boolean;`);
      }
    }

    lines.push('}');
    lines.push('');

    // Generate event types
    lines.push(`export type ${machine.name}Event = ${machine.events.map(e => `'${e}'`).join(' | ')};`);
    lines.push('');

    // Generate action functions
    for (const action of actions) {
      lines.push(this.generateAction(action, machine));
      lines.push('');
    }

    return lines.join('\n');
  }

  generateAction(action: ActionScaffold, machine: MachineDef): string {
    const ctxType = 'Context';

    if (action.hasEffect && action.effectType) {
      return `// Action: ${action.name}
// Effect: ${action.effectType}

export function ${action.name}(ctx: ${ctxType}, event: { type: ${machine.name}Event }): [${ctxType}, Effect<${action.effectType}>] {
  // TODO: Implement action
  return [ctx, { type: '${action.effectType}', payload: {} }];
}`;
    }

    return `// Action: ${action.name}

export function ${action.name}(ctx: ${ctxType}): ${ctxType} {
  // TODO: Implement action
  return { ...ctx };
}`;
  }
}

// Register the TypeScript code generator
import { registerCodeGenerator } from './registry.js';
registerCodeGenerator('typescript', () => new TypeScriptCodeGenerator());
