/**
 * GitHub effect — creates pull requests via the `gh` CLI.
 */

import { execSync } from 'child_process';
import type { PhaseStep } from '../types.js';

export interface PRResult {
  url: string;
}

/**
 * Create a pull request for the completed phase steps.
 * Requires the `gh` CLI to be installed and authenticated.
 */
export function createPullRequest(
  repoRoot: string,
  completedSteps: PhaseStep[],
  phaseTitle: string
): PRResult {
  const stepList = completedSteps
    .map(s => `- Step ${s.id}: ${s.title}`)
    .join('\n');

  const title = `Implement ${phaseTitle} (${completedSteps.map(s => s.id).join(', ')})`;

  const body = `## Summary

Automated implementation of phase steps via orca-workflow.

${stepList}

## Steps implemented

${completedSteps
  .map(s => `### Step ${s.id}: ${s.title}\n\n**Deliverable:** ${s.deliverable}`)
  .join('\n\n')}

---
*Generated by \`@orca-lang/workflow-ts\`*`;

  const escapedTitle = title.replace(/"/g, '\\"');
  const escapedBody = body.replace(/"/g, '\\"');

  try {
    const url = execSync(
      `gh pr create --title "${escapedTitle}" --body "${escapedBody}"`,
      { cwd: repoRoot, encoding: 'utf-8' }
    ).trim();
    return { url };
  } catch (err: unknown) {
    const execErr = err as { stderr?: string };
    throw new Error(`Failed to create PR: ${execErr.stderr ?? String(err)}`);
  }
}
